package com.example.springAI.service;

import java.util.List;
import java.util.Map;
import java.util.ArrayList;

public final class MongoDBPromptBuilder {

    private MongoDBPromptBuilder() {
    }

    /**
     * Stage 1 (qwen2.5-coder:7b):
     * Parsed MongoDB query -> explanation of the deterministic SQL conversion.
     *
     * IMPORTANT:
     * The Java MongoDB parser/converter is the source of truth.
     * Ollama must NOT invent or modify SQL.
     */
    public static String buildSqlConversionPrompt(
            String mongoQuery,
            String parsedMongoQuery,
            String sqlQuery
    ) {

        return """
                You are a precise MongoDB-to-SQL explanation engine
                for TRIQL, a visual query learning platform.

                The MongoDB query has already been parsed by a
                deterministic Java parser and converted to SQL by a
                deterministic Java converter.

                Your task is ONLY to explain the already-generated
                SQL. You must NOT generate, modify, correct, or
                replace the SQL.

                Original MongoDB query:
                %s

                Parsed MongoDB query:
                %s

                Deterministic SQL generated by the Java converter:
                %s

                STRICT RULES:

                1. The deterministic SQL above is the ONLY valid SQL.
                   Never modify it.

                2. Do NOT invent tables or columns.

                3. Do NOT add filters, sorting, grouping, joins,
                   limits, projections, or aggregations that are
                   not present in the generated SQL.

                4. Explain how the MongoDB operation maps to the
                   SQL operation.

                5. MongoDB find() maps to SELECT.

                6. MongoDB filter conditions map to WHERE.

                7. MongoDB projection maps to SELECT columns.

                8. MongoDB sort() maps to ORDER BY.

                9. MongoDB limit() maps to LIMIT.

                10. MongoDB skip() maps to OFFSET.

                11. countDocuments() maps to COUNT(*).

                12. $match maps to WHERE.

                13. $group maps to GROUP BY and SQL aggregate
                    functions such as SUM, AVG, MIN, MAX, or COUNT.

                14. $lookup maps to a relational JOIN.

                15. $in / $nin map to WHERE ... IN (...) / NOT IN (...).

                16. $or / $and map to WHERE conditions combined with
                    OR / AND.

                17. $exists maps to WHERE ... IS NOT NULL / IS NULL.

                18. $regex maps to WHERE ... LIKE.

                19. $unwind maps to a JOIN against a related table —
                    this mapping is a best-effort assumption, not a
                    verified schema relationship; mention this
                    caveat when explaining $unwind specifically.

                20. Explain only operations that actually exist in
                    the MongoDB query.

                21. If the query uses multiple operations, explain
                    how they work together.

                22. Keep the explanation beginner-friendly.

                23. Do not execute the query.

                24. Do not fabricate result rows or row counts.

                25. Output ONLY raw JSON.

                Required JSON structure:

                {
                  "explanation": "short beginner-friendly explanation"
                }
                """.formatted(
                mongoQuery,
                parsedMongoQuery,
                sqlQuery
        );
    }


    /**
     * Stage 2 (qwen2.5:7b):
     * MongoDB query + deterministic SQL -> logical execution steps.
     */
    /**
     * Stage 2 (qwen2.5:7b):
     * MongoDB query + deterministic SQL -> logical execution steps.
     */
    public static String buildStepsPrompt(
            String mongoQuery,
            String sqlQuery,
            String parsedMongoQuery
    ) {

        String lowerMongo = mongoQuery.toLowerCase();

        List<String> operations = new ArrayList<>();

        boolean hasFind = lowerMongo.contains(".find(");
        boolean hasCount = lowerMongo.contains(".countdocuments(");
        boolean hasWhere = lowerMongo.contains("$match") || hasFindFilter(mongoQuery);
        boolean hasSelect = hasProjection(mongoQuery);
        boolean hasGroup = lowerMongo.contains("$group");
        boolean hasSort = lowerMongo.contains(".sort(") || lowerMongo.contains("$sort");
        boolean hasOffset = lowerMongo.contains(".skip(") || lowerMongo.contains("$skip");
        boolean hasLimit = lowerMongo.contains(".limit(") || lowerMongo.contains("$limit");
        boolean hasJoin = lowerMongo.contains("$lookup");
        boolean hasUnwind = lowerMongo.contains("$unwind");

        if (hasFind) operations.add("FIND");
        if (hasCount) operations.add("COUNT");
        if (hasWhere) operations.add("WHERE");
        if (hasSelect) operations.add("SELECT");
        if (hasGroup) { operations.add("GROUP BY"); operations.add("AGGREGATE"); }
        if (hasSort) operations.add("ORDER BY");
        if (hasOffset) operations.add("OFFSET");
        if (hasLimit) operations.add("LIMIT");
        if (hasJoin) operations.add("JOIN");
        if (hasUnwind) operations.add("UNWIND");

        StringBuilder checklist = new StringBuilder();
        for (String op : operations) {
            checklist.append("- ").append(op).append("\n");
        }

        int checklistCount = operations.size();

        // -----------------------------------------------------
        // Dynamically build "do not merge" warnings only for
        // operation pairs that actually co-occur in this query,
        // instead of one fixed example irrelevant to other shapes.
        // -----------------------------------------------------

        StringBuilder mergeWarnings = new StringBuilder();

        if (hasFind && hasWhere) {
            mergeWarnings.append(
                    "- FIND and WHERE are ALWAYS two separate steps, "
                            + "even though they appear in the same find({...}) "
                            + "call and even though the resulting SQL puts "
                            + "SELECT/FROM and WHERE in one statement. Never "
                            + "describe both the retrieval and the filter "
                            + "condition inside a single step's description.\n"
            );
        }

        if (hasGroup) {
            mergeWarnings.append(
                    "- GROUP BY and AGGREGATE are ALWAYS two separate "
                            + "steps, even though a single $group stage "
                            + "produces both the grouping and the aggregate "
                            + "function together.\n"
            );
        }

        if (hasJoin && hasWhere) {
            mergeWarnings.append(
                    "- JOIN and WHERE are ALWAYS two separate steps, "
                            + "even when $lookup and $match both appear in "
                            + "the same aggregation pipeline.\n"
            );
        }

        if (hasSort && hasLimit) {
            mergeWarnings.append(
                    "- ORDER BY and LIMIT are ALWAYS two separate steps, "
                            + "even when sort() and limit() are chained "
                            + "together in the same query.\n"
            );
        }

        if (hasOffset && hasLimit) {
            mergeWarnings.append(
                    "- OFFSET and LIMIT are ALWAYS two separate steps, "
                            + "even when skip() and limit() are chained "
                            + "together in the same query.\n"
            );
        }

        if (mergeWarnings.isEmpty()) {
            mergeWarnings.append(
                    "- Every operation in the checklist above gets its "
                            + "own step. Never combine two operations, even "
                            + "if they appear close together in the query or "
                            + "in the same SQL statement.\n"
            );
        }

        // -----------------------------------------------------
        // Dynamically build a worked example skeleton showing
        // exactly checklistCount steps, using this query's own
        // operations — not a fixed unrelated example.
        // -----------------------------------------------------

        StringBuilder exampleSteps = new StringBuilder();
        for (int i = 0; i < operations.size(); i++) {
            String op = operations.get(i);
            exampleSteps.append("    {\n")
                    .append("      \"operation\": \"").append(op).append("\",\n")
                    .append("      \"mongodb\": \"<fragment for ").append(op).append(">\",\n")
                    .append("      \"sql\": \"<fragment for ").append(op).append(">\",\n")
                    .append("      \"description\": \"<explains only ").append(op).append(">\"\n")
                    .append("    }")
                    .append(i < operations.size() - 1 ? ",\n" : "\n");
        }

        return """
            You are an educational assistant for TRIQL,
            a visual MongoDB-to-SQL learning platform.

            Your task is to explain the logical execution
            of the MongoDB query by matching each MongoDB
            operation to its SQL counterpart.

            Original MongoDB query:
            %s

            Parsed MongoDB query:
            %s

            Deterministic SQL:
            %s

            The MongoDB query contains EXACTLY these
            operations:

            %s

            You MUST produce EXACTLY %d step object(s) — one
            step for EACH operation listed above, never fewer,
            never combined into one step.

            CRITICAL — DO NOT MERGE STEPS:
            %s
            REQUIRED SHAPE FOR THIS QUERY (fill in the real
            fragments and descriptions — do not leave the
            placeholder text, and do not add, remove, merge,
            or reorder these %d steps):

            {
              "explanation": "one short paragraph",
              "steps": [
            %s
              ]
            }

            STRICT RULES:

            1. Include every operation in the checklist —
               exactly %d steps total, no more, no fewer.

            2. Do NOT add operations that are not present
               in the checklist.

            3. Do NOT invent MongoDB operations.

            4. Do NOT modify the deterministic SQL.

            5. Each MongoDB operation must correspond to
               the correct SQL fragment.

            6. find() maps to SELECT/FROM.

            7. MongoDB filter conditions map to WHERE.

            8. Projection maps to SELECT columns.

            9. sort() maps to ORDER BY.

            10. skip() maps to OFFSET.

            11. limit() maps to LIMIT.

            12. countDocuments() maps to COUNT(*).

            13. $match maps to WHERE.

            14. $group maps to GROUP BY.

            15. MongoDB aggregation operators such as
                $sum, $avg, $min and $max map to SQL
                aggregate functions.

            16. $lookup maps to JOIN.

            17. $in / $nin map to WHERE ... IN (...) / NOT IN (...).

            18. $or / $and map to WHERE conditions combined with
                OR / AND.

            19. $exists maps to WHERE ... IS NOT NULL / IS NULL.

            20. $regex maps to WHERE ... LIKE.

            21. $unwind maps to a JOIN against a related table —
                this mapping is a best-effort assumption, not a
                verified schema relationship; mention this
                caveat when the step describes $unwind
                specifically.

            22. Do NOT fabricate row counts.

            23. Do NOT generate sample data.

            24. Do NOT execute the query.

            25. Each "mongodb" field must contain only the
                relevant MongoDB fragment.

            26. Each "sql" field must contain only the
                relevant SQL fragment.

            27. Each description must be 1-2 simple sentences,
                describing ONLY its own operation — never
                describe another step's operation inside a
                different step's description.

            28. Keep the execution order logical.

            29. Before finalizing, count your steps and
                compare the count against the checklist above.
                If the counts do not match, add or split steps
                until they do.

            30. Output ONLY raw JSON.
            """.formatted(
                mongoQuery,
                parsedMongoQuery,
                sqlQuery,
                checklist.toString(),
                checklistCount,
                mergeWarnings.toString(),
                checklistCount,
                exampleSteps.toString(),
                checklistCount
        );
    }


    /**
     * Stage 3 (qwen2.5:3b):
     * Generate relational sample data.
     */
    public static String buildSampleDataPrompt(
            String mongoQuery,
            String sqlQuery,
            Map<String, List<String>> requiredColumns
    ) {

        return """
                You are generating small sample relational data
                for TRIQL, a visual MongoDB-to-SQL learning platform.

                The generated data will be displayed interactively
                in a query visualization.

                The data MUST demonstrate the actual operations
                contained in the MongoDB query.

                Original MongoDB query:
                %s

                Equivalent deterministic SQL:
                %s

                Required relational schema
                (table name -> exact column list):
                %s

                STRICT RULES:

                1. Use ONLY tables present in the required schema.

                2. Use ONLY columns present in the required schema.

                3. Do NOT add, remove, rename, or invent columns.

                4. Generate exactly 3 to 5 rows for every table.

                5. Every required column must have a value.

                6. Do not use null, empty strings, N/A, TBD,
                   unknown, or placeholder values.

                7. Use realistic values.

                8. Keep all foreign-key relationships consistent.

                9. If the query contains a filter, generate both
                   matching and non-matching values whenever
                   possible.

                Example:

                MongoDB:
                db.users.find({age: {$gt: 25}})

                Generate some users with age > 25 and some users
                with age <= 25.

                10. If the query contains multiple conditions,
                    generate rows that:
                    - satisfy all conditions
                    - fail at least one condition

                11. If the query contains sort(), generate
                    different values for the sorted column so
                    the sorting effect is visible.

                12. If the query contains limit(), generate
                    enough rows so that LIMIT is visible.

                13. If the query contains skip(), generate
                    enough rows so that OFFSET is visible.

                14. If the query contains $match, generate both
                    matching and non-matching rows.

                15. If the query contains $group, generate
                    repeated values for the grouping field so
                    multiple documents belong to the same group.

                16. If the query contains $sum, generate
                    different numeric values so the total is
                    meaningful.

                17. If the query contains $avg, generate
                    different numeric values so the average
                    is meaningful.

                18. If the query contains $min or $max, generate
                    different numeric values so the minimum and
                    maximum are visible.

                19. If the query contains $lookup, make sure
                    matching foreign-key values exist in the
                    referenced table.

                20. For $lookup, also include at least one
                    meaningful relationship that demonstrates
                    the JOIN.

                21. If the query uses $in or $nin, generate some
                    rows whose field value IS in the list and
                    some rows whose value is NOT in the list, so
                    the inclusion/exclusion effect is visible.

                22. If the query uses $or, generate rows that
                    satisfy only the first sub-condition, rows
                    that satisfy only the second sub-condition,
                    and rows that satisfy neither — so it is
                    clear the match is not simple AND logic.

                23. If the query uses $and, generate rows that
                    satisfy all sub-conditions together and rows
                    that satisfy only some of them, so the
                    combined filter's effect is visible.

                24. If the query uses $exists, generate some rows
                    where the field is present with a real value
                    and, where the schema allows, some rows that
                    represent the field being absent (use a
                    clearly distinguishable value such as a
                    sentinel/default only if the schema requires
                    a non-null column; otherwise vary presence
                    honestly).

                25. If the query uses $regex, generate some
                    values that match the pattern and some that
                    clearly do not, so the pattern's filtering
                    effect is visible.

                26. If the query uses $unwind and the required
                    schema includes a separate child/related
                    table for the unwound field, generate multiple
                    child rows per parent row (varying counts
                    across parents — at least one parent with 2+
                    child rows) so the flattening effect of
                    $unwind is visible.

                27. If the query combines $lookup and $group in
                    the same pipeline, ensure the generated data
                    supports both: matching foreign keys for the
                    join AND repeated group-field values so the
                    grouping is meaningful after the join.

                28. Do NOT generate SQL.

                29. Do NOT generate explanations.

                30. Do NOT generate Markdown.

                31. Output ONLY raw JSON.

                32. Preserve numeric values as JSON numbers.

                33. Preserve text values as JSON strings.

                34. Do not include tables outside the required
                    schema.

                35. Do not include columns outside the required
                    schema.

                Required JSON structure:

                {
                  "tables": {
                    "TableName": [
                      {
                        "column1": "value",
                        "column2": 123
                      }
                    ]
                  }
                }
                """.formatted(
                mongoQuery,
                sqlQuery,
                requiredColumns
        );
    }


    /**
     * Stage 4:
     * Validate generated execution steps.
     */
    public static String buildValidationPrompt(
            String candidateJson,
            String mongoQuery,
            String sqlQuery
    ) {

        return """
                You are a strict correctness validator for TRIQL's
                MongoDB-to-SQL visualization pipeline.

                Original MongoDB query:
                %s

                Deterministic SQL:
                %s

                Candidate execution steps:
                %s

                Validate every step against the original MongoDB
                query and deterministic SQL.

                STRICT RULES:

                1. Do NOT approve an operation that is absent
                   from the MongoDB query.

                2. find() must represent document retrieval.

                3. MongoDB filter conditions must represent
                   WHERE filtering.

                4. Projection must represent SELECT columns.

                5. sort() must represent ORDER BY.

                6. skip() must represent OFFSET.

                7. limit() must represent LIMIT.

                8. countDocuments() must represent COUNT(*).

                9. $match must represent WHERE.

                10. $group must represent GROUP BY.

                11. $sum, $avg, $min and $max must represent
                    their corresponding SQL aggregate functions.

                12. $lookup must represent JOIN.

                13. Do NOT allow a step to introduce SQL that
                    does not exist in the deterministic SQL.

                14. Step order must follow the actual logical
                    operations present in the MongoDB query.

                15. Set "valid" to true ONLY when every step
                    is correct.

                16. correctedSteps must contain ONLY steps that
                    require correction.

                17. Output ONLY raw JSON.

                Required JSON structure:

                {
                  "valid": false,
                  "issues": [
                    "short description of problem"
                  ],
                  "correctedSteps": [
                    {
                      "operation": "WHERE",
                      "mongodb": "relevant MongoDB fragment",
                      "sql": "relevant SQL fragment",
                      "description": "corrected explanation"
                    }
                  ]
                }
                """.formatted(
                mongoQuery,
                sqlQuery,
                candidateJson
        );
    }


    /**
     * Standalone MongoDB syntax-error explanation.
     */
    public static String buildSyntaxErrorPrompt(
            String mongoQuery,
            String errorMessage
    ) {

        return """
                You are a MongoDB syntax explanation assistant
                for TRIQL.

                Help a beginner understand why their MongoDB
                query could not be parsed.

                User MongoDB query:
                %s

                Parser error:
                %s

                STRICT RULES:

                1. Explain only the actual parser error.

                2. Do not invent database schema.

                3. Do not assume collections or fields that are
                   not present in the query.

                4. Do not rewrite the entire query unless a
                   very small correction is necessary.

                5. Keep each field to 1-2 sentences.

                6. Output ONLY raw JSON.

                Required JSON structure:

                {
                  "error": "short explanation",
                  "reason": "why it happened",
                  "suggestion": "how to fix it"
                }
                """.formatted(
                mongoQuery,
                errorMessage
        );
    }


    // ============================================================
    // HELPER METHODS
    // ============================================================

    private static boolean hasFindFilter(
            String query
    ) {

        String lower = query.toLowerCase();

        int findIndex =
                lower.indexOf(".find(");

        if (findIndex < 0) {
            return false;
        }

        int start =
                findIndex + ".find(".length();

        int end =
                query.indexOf(")", start);

        if (end < 0) {
            return false;
        }

        String inside =
                query.substring(start, end).trim();

        return !inside.isEmpty()
                && !inside.equals("{}");
    }


    private static boolean hasProjection(
            String query
    ) {

        String lower =
                query.toLowerCase();

        int findIndex =
                lower.indexOf(".find(");

        if (findIndex < 0) {
            return false;
        }

        int start =
                findIndex + ".find(".length();

        int end =
                query.indexOf(")", start);

        if (end < 0) {
            return false;
        }

        String inside =
                query.substring(start, end);

        /*
         * A second object after the first find() argument
         * represents projection.
         */
        int comma =
                inside.indexOf(",");

        return comma >= 0
                && inside.substring(
                comma + 1
        ).trim().startsWith("{");
    }
}